export default {
    ts: "TypeScript",
    js: "JavaScript",
    python: "Python",
    sqlite: "SQLite",
    mongo: "MongoDB",
    postgreSql: "PostgreSQL",
    html: "HTML",
    css: "CSS",
    sass: "SASS",
    scss: "SCSS",
    less: "Less",
    stylus: "Stylus",
    ejs: "EJS",
    jinja: "Jinja2",
    node: "Node.js",
    vscode: "VSCode",
    nvim: "NeoVim",
    figma: "Figma",
    git: "Git & GitHub",
    xfce: "XFCE",
    react: "React",
    discordJs: "Discord.js",
    flask: "Flask",
    quart: "Quart",
    express: "Express",
    rtk: "RTK",
    zod: "Zod",
    webpack: "WebPack",
    pug: "Pug",
    gulp: "Gulp",
    next: "Next",
    deno: "Deno",
    pixijs: "PixiJS",
    preact: "Preact",
    python: "Python",
    pandas: "Pandas",
    scikitLearn: "Scikit-learn",
    yfinance: "yFinance",
    numpy: "NumPy",
    plot: "Plotly",
    firebase: "Firebase",
    reactNative: "React Native",
    powerBi: "Power BI",
    DAX: "DAX",
    PowerQuery: "Power Query",
    microsoftSql: "Microsoft SQL Server",
    spark: "Apache Spark",
    methodeAgile: "Méthode Agile",
    Trello: "Trello",
    figma: "Figma",
    UML: "UML",
    merise: "Merise",
    Vujs: "Vue.js",
    sql_server: "SQL Server",
    exel:"Excel" ,
    kedro:"Kedro",
    mlflow:"MLflow",
    shell:"Shell",
    prisma:"Prisma",
    css:"CSS",
    VBA:"VBA",
    mlflow:"MLflow",
    shell:"Shell",
    sql:"SQL",
    ETL:"ETL/ELT",
    Jira:"Jira",
    Selenium:"Selenium",
    sonaque:"SonarQube",
    git:"GitHub/GitLab",


}